version: 2
updates:
  # Python dependencies - VERSION UPDATES ONLY (Security handled by Trivy)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "version-update"
      - "trivy-security-scanning"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Only allow patch and minor version updates (excludes major security updates)
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates (where most security fixes are published)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker base image updates - VERSION UPDATES ONLY (Security handled by Trivy)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 2
    labels:
      - "docker"
      - "version-update"
      - "trivy-security-scanning"
    commit-message:
      prefix: "docker"
      include: "scope"
    # Allow all dependency types but ignore major updates
    allow:
      - dependency-type: "direct"
    # Ignore major version updates (where most security fixes are published)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions updates - FULL UPDATES INCLUDING SECURITY
  # (Actions security is still important for CI/CD pipeline security)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # GitHub Actions - allow all updates including security
    allow:
      - dependency-type: "all"
