version: 2
updates:
  # Python dependencies - DISABLED security scanning
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group non-security updates
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "mcp*"
          - "requests"
          - "aiohttp"
        update-types:
          - "patch"
    # ONLY allow non-security updates (disable security alerts)
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-patch"]

  # Docker base image updates - DISABLED security scanning
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "security-team"
    labels:
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    # ONLY allow non-security updates
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]

  # GitHub Actions updates - Keep security scanning for actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
