version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "security"
      include: "scope"
    # Group non-security updates
    groups:
      development-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "ruff"
          - "mypy"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "mcp*"
          - "requests"
          - "aiohttp"
        update-types:
          - "patch"
    # Automatically approve security updates
    allow:
      - dependency-type: "all"

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "security-team"
    labels:
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"
      include: "scope"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    labels:
      - "github-actions"
      - "security"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch" 