apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-schema-registry-mcp.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-schema-registry-mcp.labels" . | nindent 4 }}
  {{- include "kafka-schema-registry-mcp.annotations" . | nindent 4 }}
data:
  # Application settings
  VIEWONLY: {{ .Values.app.viewonly | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  
  # OAuth2 settings
  {{- if .Values.auth.enabled }}
  ENABLE_AUTH: "true"
  AUTH_ISSUER_URL: {{ .Values.auth.oauth2.issuerUrl | quote }}
  AUTH_VALID_SCOPES: {{ .Values.auth.oauth2.validScopes | quote }}
  AUTH_DEFAULT_SCOPES: {{ .Values.auth.oauth2.defaultScopes | quote }}
  AUTH_REQUIRED_SCOPES: {{ .Values.auth.oauth2.requiredScopes | quote }}
  AUTH_CLIENT_REG_ENABLED: {{ .Values.auth.oauth2.clientRegistrationEnabled | quote }}
  AUTH_REVOCATION_ENABLED: {{ .Values.auth.oauth2.revocationEnabled | quote }}
  {{- else }}
  ENABLE_AUTH: "false"
  {{- end }}
  
  # Schema Registry settings
  SCHEMA_REGISTRY_URL: {{ .Values.schemaRegistry.url | quote }}
  
  {{- if .Values.schemaRegistry.multiRegistry.enabled }}
  # Multi-registry configuration
  {{- range $index, $registry := .Values.schemaRegistry.multiRegistry.registries }}
  {{- $registryIndex := add $index 1 }}
  SCHEMA_REGISTRY_NAME_{{ $registryIndex }}: {{ $registry.name | quote }}
  SCHEMA_REGISTRY_URL_{{ $registryIndex }}: {{ $registry.url | quote }}
  VIEWONLY_{{ $registryIndex }}: {{ $registry.viewonly | quote }}
  {{- end }}
  {{- end }}
  
  {{- with .Values.extraEnvVars }}
  # Additional environment variables
  {{- range . }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
  {{- end }} 