{{- if and .Values.monitoring.enabled .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kafka-schema-registry-mcp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka-schema-registry-mcp.labels" . | nindent 4 }}
    {{- with .Values.monitoring.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - port: http
    path: {{ .Values.monitoring.podMonitor.path | default "/metrics" }}
    interval: {{ .Values.monitoring.podMonitor.interval | default "30s" }}
    scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout | default "10s" }}
    honorLabels: {{ .Values.monitoring.podMonitor.honorLabels | default false }}
    {{- with .Values.monitoring.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.monitoring.podMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-schema-registry-mcp.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  {{- with .Values.monitoring.podMonitor.podTargetLabels }}
  podTargetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  sampleLimit: {{ .Values.monitoring.podMonitor.sampleLimit | default 0 }}
  targetLimit: {{ .Values.monitoring.podMonitor.targetLimit | default 0 }}
{{- end }} 