name: Tag as Stable

on:
  workflow_dispatch:
    inputs:
      source_tag:
        description: 'Existing tag to promote to stable (e.g., v1.3.0, v1.2.1, latest)'
        required: true
        type: string

jobs:
  tag-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify source image exists
        run: |
          echo "🔍 Verifying that source image exists..."
          SOURCE_TAG="${{ github.event.inputs.source_tag }}"
          
          # Pull the source image to verify it exists
          if docker pull aywengo/kafka-schema-reg-mcp:${SOURCE_TAG}; then
            echo "✅ Source image aywengo/kafka-schema-reg-mcp:${SOURCE_TAG} exists"
          else
            echo "❌ Source image aywengo/kafka-schema-reg-mcp:${SOURCE_TAG} does not exist"
            echo "Available tags can be found at: https://hub.docker.com/r/aywengo/kafka-schema-reg-mcp/tags"
            exit 1
          fi

      - name: Re-tag as stable
        run: |
          echo "🏷️ Promoting ${{ github.event.inputs.source_tag }} to stable..."
          SOURCE_TAG="${{ github.event.inputs.source_tag }}"
          
          # Tag the existing image as stable
          docker tag aywengo/kafka-schema-reg-mcp:${SOURCE_TAG} aywengo/kafka-schema-reg-mcp:stable
          
          # Push the stable tag
          docker push aywengo/kafka-schema-reg-mcp:stable
          
          echo "✅ Successfully promoted ${SOURCE_TAG} to stable!"

      - name: Verify stable tag
        run: |
          echo "🔍 Verifying stable tag was created..."
          if docker pull aywengo/kafka-schema-reg-mcp:stable; then
            echo "✅ Stable tag verified successfully"
            
            # Get image digest for confirmation
            STABLE_DIGEST=$(docker inspect aywengo/kafka-schema-reg-mcp:stable --format='{{index .RepoDigests 0}}')
            SOURCE_DIGEST=$(docker inspect aywengo/kafka-schema-reg-mcp:${{ github.event.inputs.source_tag }} --format='{{index .RepoDigests 0}}')
            
            echo "📋 Image Digests:"
            echo "   Source (${{ github.event.inputs.source_tag }}): ${SOURCE_DIGEST}"
            echo "   Stable: ${STABLE_DIGEST}"
            
            if [ "${STABLE_DIGEST}" = "${SOURCE_DIGEST}" ]; then
              echo "✅ Digests match - promotion successful!"
            else
              echo "⚠️ Digests don't match - this might be normal due to DockerHub processing"
            fi
          else
            echo "❌ Failed to verify stable tag"
            exit 1
          fi

      - name: Summary
        run: |
          echo "🎉 Tag Promotion Complete!"
          echo ""
          echo "📋 Summary:"
          echo "   Source tag: ${{ github.event.inputs.source_tag }}"
          echo "   Target tag: stable"
          echo "   Repository: aywengo/kafka-schema-reg-mcp"
          echo ""
          echo "🐳 Usage:"
          echo "   docker pull aywengo/kafka-schema-reg-mcp:stable"
          echo ""
          echo "🔗 DockerHub: https://hub.docker.com/r/aywengo/kafka-schema-reg-mcp/tags" 